### ISSUE TITLE
网站搜索功能

### ISSUE THREAD

**Issue by imuncle** [imuncle/imuncle.github.io#42]
随着博客写的越来越多，寻找内容越来越麻烦，于是萌生出了做一个文章搜索的功能。

# GitHub API
在查阅了GitHub API后，发现可以很方便地搜索issue，repository，commit，author等，还支持多条件查询，可以说是非常方便了，详情见[Search | GitHub Developer Guide](https://developer.github.com/v3/search/)

我这里只需要查询我自己发布的issue，这里的查询条件有以下五个：

* 查询关键词
* 作者：imuncle
* 对象：open状态的issue
* 范围：标题和内容
* 排序：匹配程度递减排序

所以我的查询链接为：
```javascript
var search_url = 'https://api.github.com/search/issues?q='+search+' author:imuncle+in:title,body+is:open+is:public+sort:interactions';
```

关于以上的查询条件设置可以查看这两个链接了解：

* [Searching issues and pull requests](https://help.github.com/en/articles/searching-issues-and-pull-requests#search-within-a-users-or-organizations-repositories)
* [Sorting search results](https://help.github.com/en/articles/sorting-search-results)

# UI设计
具体的UI实现就在小站的每个页面的右上角，位于菜单按钮下方，实现代码如下：

* HTML
```html
<input type="text" class="search-input" placeholder="回车搜索" onblur="searchOnblur()">
<img src="images/search.svg" class="search">
```
* css
```css
.search {
    opacity: 0.6;
    position: fixed;
    right: 20px;
    top: 60px;
    cursor: pointer;
    z-index: 99;
    width: 35px;
    transition: all 0.4s;
}
.search-input {
    width: 42px;
    height: 42px;
    padding-left: 15px;
    border-radius: 42px;
    border: 1px solid rgba(127,140,141,0.6);
    background: white;
    outline: none;
    position: relative;
    transition: all 0.4s;
    position: fixed;
    right: 10px;
    top: 57px;
    z-index: -1;
}
```
* javascript
```javascript
$('.search').click(function() {
    $(".search-input").css('z-index',99);
    $(".search-input").css("width",'300px');
    $(".search-input").focus();
});

function searchOnblur(){
    if($('.search-input').val() == "")
    {
        $(".search-input").css("width",'42px');
        $(".search-input").css("z-index",-1);
    }
}

$('.search-input').bind('keypress', function (event) { 
    if (event.keyCode == "13" && $('.search-input').val() != "") {
        window.location.href = 'issue_per_label.html?q='+$('.search-input').val();
    }
})
```

# 关键词高亮
开始我只高亮了完全匹配搜索关键词的地方，效果如下：
![image](https://user-images.githubusercontent.com/35989223/54874642-6add6d00-4e2a-11e9-887b-d40083508bfb.png)

可以看到除了前两条搜索结果，后面的搜索结果似乎都没有出现`步进电机`这个关键词，仔细阅读其他搜索结果发现文章中出现了`步进电机`中的某一个或几个字，导致被检索到，所以我决定把搜索的关键词拆分成单个字，挨个高亮。

顺便一提，GitHub搜索是支持多个关键词的，只需要空格分开就行了，所以高亮之前要把搜索关键词中的空格删掉。

具体的实现代码如下：

```javascript
var html = document.getElementById('issue-list').innerHTML;
search = search.replace(/\s*/g,"");
for(var i=0;i<search.length;i++) {
   var newHtml = html.replaceAll(search[i],'<font style="background-color:yellow;">'+search[i]+'</font>');
   document.getElementById('issue-list').innerHTML = newHtml;
}
```

修改之后的效果如下：
![image](https://user-images.githubusercontent.com/35989223/54874754-6ca83000-4e2c-11e9-9ac2-37c07f5316e7.png)
